#include "main.h"
#include <stdio.h>
#include <stdlib.h>
#include "gba.h"
#define RED COLOR(31, 0, 0)
/* TODO: */
// Include any header files for title screen or exit
// screen images generated by nin10kit. Example for the provided garbage
// image:
// #include "images/garbage.h"
// #include "images/homescreen.h"
#include "images/welcomescreen.h"
#include "images/lose.h"
#include "images/win.h"
#include "images/road.h"
#include "images/straws.h"
#include "images/player5.h"

/* TODO: */
// Add any additional states you need for your app. You are not requried to use
// these specific provided states.
enum gba_state {
  START,
  PLAY,
  WIN,
  WIN2,
  LOSE,
};

enum gba_state state = START;
int time = 0;
char name[50];

int main(void) {
  /* TODO: */
  // Manipulate REG_DISPCNT here to set Mode 3. //
  REG_DISPCNT = MODE3 | BG2_ENABLE;
  // Save current and previous state of button input.
  u32 previousButtons = BUTTONS;
  u32 currentButtons = BUTTONS;

  // Load initial application state
  // enum gba_state state = START;
  while (1) {
    currentButtons = BUTTONS; // Load the current state of the buttons

    /* TODO: */
    // Manipulate the state machine below as needed //
    // NOTE: Call waitForVBlank() before you draw
    waitForVBlank();

    switch (state) {
      case START:
        drawImageDMA(0, 0, 240, 160, welcomescreen);
        if (KEY_DOWN(BUTTON_START, currentButtons)) {
          state = PLAY;
        }
        break;
      case PLAY:
        time = 0;
        vBlankCounter = 0;
        fillScreenDMA(BLACK);
        makeGame();
        break;
      case WIN:
        drawImageDMA(0, 0, 240, 160, win);
        state = WIN2;
        break;
      case WIN2: ;
        // drawImageDMA(0, 0, 240, 160, win);
        char str[40];
        sprintf(str, "You took this many seconds: %d", time);
        drawString(120, 30, str, WHITE);
        if (KEY_DOWN(BUTTON_SELECT, currentButtons)) {  
          fillScreenDMA(BLACK);
          state = START;
        }
        break;
      case LOSE:
        drawImageDMA(0, 0, 240, 160, lose);
        if (KEY_DOWN(BUTTON_SELECT, currentButtons)) {  
          state = START;
        }
        break;
    }

    previousButtons = currentButtons; // Store the current state of the buttons
  }

  UNUSED(previousButtons); // You can remove this once previousButtons is used

  return 0;
}

Player makePlayer(void) {
  Player character;
  character.x = 10;
  character.y = 20;
  drawImageDMA(character.x, character.y, 10, 10, player5);
  return character;
}

struct goalBlock makeGoal(void) {
  struct goalBlock goals;
  goals.x = 140;
  goals.y = 220;
  drawRectDMA(140, 220, 20, 20, WHITE);
  drawImageDMA(goals.x, goals.y, 20, 20, straws);
  return goals;
}

void makeMaze(void) {
  // drawRectDMA(30, 0, 200, 1, BLACK);
  drawImageDMA(30, 0, 200, 5, road);
  // drawRectDMA(60, 40, 200, 1, BLACK);
  drawImageDMA(60, 40, 200, 5, road);
  // drawRectDMA(90, 0, 200, 1, BLACK);
  drawImageDMA(90, 0, 200, 5, road);
  // drawRectDMA(120, 40, 200, 1, BLACK);
  drawImageDMA(120, 40, 200, 5, road);

}

void makeGame(void) {
  Player character = makePlayer();
  struct goalBlock goals = makeGoal();
  drawImageDMA(character.x, character.y, 10, 10, player5);
  u32 buttons;
  makeMaze();

  while(1) {
     waitForVBlank();
     time = vBlankCounter/60;
     char str[40]; 
     sprintf(str, "Time Left: %d", (15 - time));
     drawRectDMA(150, 60, 100, 100, BLACK);
     drawString(150, 60, str, WHITE);

     buttons = BUTTONS;
     if (KEY_DOWN(BUTTON_LEFT, buttons)) { 
        drawRectDMA(character.x, character.y, 10, 10, BLACK);
        character.y-=2;
        if (character.y <= 0) {
          character.y = 0;
        }
        if ((character.x >= 20 && character.x <=35) && character.y <= 200) {
          character.y += 2;
          // state = LOSE;
          // break;
        }
        if ((character.x >= 80 && character.x <=95) && character.y <= 200) {
          character.y += 2;
          // state = LOSE;
          // break;
        }
        if ((character.x >= 50 && character.x <=65) && character.y >= 40) {
          character.y += 2;
          // state = LOSE;
          // break;
        }
        if ((character.x >= 110 && character.x <=125) && character.y >= 40) {
          character.y += 2;
          // state = LOSE;
          // break;
        }
        drawImageDMA(character.x, character.y, 10, 10, player5);
      }
    if (KEY_DOWN(BUTTON_RIGHT, buttons)) { 
        drawRectDMA(character.x, character.y, 10, 10, BLACK);
        character.y+=2;
        if (character.y >= 230) {
          character.y = 230;
        }
        if ((character.x >= 20 && character.x <=35) && character.y <= 200) {
          character.y -= 2;
          // state = LOSE;
          // break;
        }
        if ((character.x >= 80 && character.x <=95) && character.y <= 200) {
          character.y -= 2;
          // state = LOSE;
          // break;
        }
        if ((character.x >= 50 && character.x <=65) && character.y >= 30) {
          character.y -= 2;
          // state = LOSE;
          // break;
        }
        if ((character.x >= 110 && character.x <=125) && character.y >= 30) {
          character.y -= 2;
          // state = LOSE;
          // break;
        }
       drawImageDMA(character.x, character.y, 10, 10, player5);
    }
    if (KEY_DOWN(BUTTON_DOWN, buttons)) { 
        drawRectDMA(character.x, character.y, 10, 10, BLACK);
        character.x+=2;
        if (character.x >= 150) {
          break;
        }
        if ((character.x >= 20 && character.x <=35) && character.y <= 200) {
          character.x -= 2;
          // state = LOSE;
          // break;
        }
        if ((character.x >= 80 && character.x <=95) && character.y <= 200) {
          character.x -= 2;
          // state = LOSE;
          // break;
        }
        if ((character.x >= 50 && character.x <=65) && character.y >= 30) {
          character.x -= 2;
          // state = LOSE;
          // break;
        }
        if ((character.x >= 110 && character.x <=125) && character.y >= 30) {
          character.x -= 2;
          // state = LOSE;
          // break;
        }

        drawImageDMA(character.x, character.y, 10, 10, player5);
    }
    if (KEY_DOWN(BUTTON_UP, buttons)) { 
        drawRectDMA(character.x, character.y, 10, 10, BLACK);
        character.x-=2;
        if (character.x <= 0) {
          character.x = 0;
        }
        if ((character.x >= 20 && character.x <=35) && character.y <= 200) {
          character.x += 2;
          // state = LOSE;
          // break;
        }
        if ((character.x >= 80 && character.x <=95) && character.y <= 200) {
          character.x += 2;
          // state = LOSE;
          // break;
        }
        if ((character.x >= 50 && character.x <=65) && character.y >= 30) {
          character.x += 2;
          // state = LOSE;
          // break;
        }
        if ((character.x >= 110 && character.x <=125) && character.y >= 30) {
          character.x += 2;
          // state = LOSE;
          // break;
        }
        drawImageDMA(character.x, character.y, 10, 10, player5);
    }

    if (15 - time <= 0) {
      state = LOSE;
      break;
    }

    if (character.x + 10 > goals.x && character.y + 10 > goals.y) {
      state = WIN;
      break;
    }

    if (KEY_DOWN(BUTTON_SELECT, buttons)) {  
      fillScreenDMA(BLACK);
      state = START;
      break;
    }

  }
}